name: 'Titan Core Snowflake infrastructure as code-xyzzy'
author: 'Titan Systems, Inc'
description: 'Deploy to Snowflake with Titan'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'orange'
