name: 'Titan Core Snowflake infrastructure as code-xyzzy'
author: 'Titan Systems, Inc'
description: 'Deploy to Snowflake with Titan'
inputs:
  run-mode:
    description: 'Run mode determines which actions can be performed. Valid options: `create-or-update` (never drops resources), `sync` (full resource control).'
    required: true
    default: 'create-or-update'
  resource-path:
    description: 'Resource path should point to the file or folder in the repo that contains the resource configuration.'
    required: true
    default: '.'
  allowlist:
    description: 'Allowlist is a comma-separated list of resource types that Titan is allowed to manage. If not provided, Titan will manage all resources.'
    required: false
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'orange'
